commit_groups:
    group_by: Type
    sort_by: Title
conventional-commits: true
deb:
    distribution: []
    urgency: ""
debug: false
exclude-merge-commits: false
notes:
    keywords:
        - BREAKING CHANGE
owner: ""
package-name: ""
sort: date
tag_filter_pattern: ^v
