services:
  php:
    build: .
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    stdin_open: true
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=typesensebundle
      - TYPESENSE_URL=http://typesense:8108
      - TYPESENSE_API_KEY=xyz
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - default
  typesense:
    links:
      - php
    image: typesense/typesense:29.0
    restart: on-failure
    volumes:
      - typesense-server-data:/data
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: xyz
      TYPESENSE_ENABLE_CORS: true
volumes:
  searchdata:
  typesense-server-data:
