services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Biblioverse\TypesenseBundle\Client\ClientSingletonFactory:
    arguments:
      $uri: '%biblioverse_typesense.config.uri%'
      $apiKey: '%biblioverse_typesense.config.key%'
      $connectionTimeoutSeconds: '%biblioverse_typesense.config.connection_timeout_seconds%'

  Biblioverse\TypesenseBundle\Client\ClientInterface:
    factory: '@Biblioverse\TypesenseBundle\Client\ClientSingletonFactory'
    lazy: true

  Biblioverse\TypesenseBundle\Populate\PopulateService: ~

  Biblioverse\TypesenseBundle\Mapper\Converter\ValueConverter: ~
  Biblioverse\TypesenseBundle\Mapper\Converter\ValueConverterInterface: '@Biblioverse\TypesenseBundle\Mapper\Converter\ValueConverter'
  Biblioverse\TypesenseBundle\Mapper\Converter\ValueExtractor: ~
  Biblioverse\TypesenseBundle\Mapper\Converter\ValueExtractorInterface: '@Biblioverse\TypesenseBundle\Mapper\Converter\ValueExtractor'


  Biblioverse\TypesenseBundle\Mapper\Locator\MapperLocator:
    public: true
    arguments:
      $collectionManagers: !tagged_locator { tag: !php/const Biblioverse\TypesenseBundle\Mapper\StandaloneCollectionManagerInterface::TAG_NAME, default_index_method: getName, index_by: 'key' }
      $dataGenerators: !tagged_locator { tag: !php/const Biblioverse\TypesenseBundle\BiblioverseTypesenseBundle::DATA_GENERATOR_TAG_NAME, index_by: 'key' }
      $mappingGenerators: !tagged_locator { tag: !php/const Biblioverse\TypesenseBundle\BiblioverseTypesenseBundle::DATA_MAPPER_GENERATOR_TAG_NAME, index_by: 'key' }
      $entityTransformers: !tagged_locator { tag: !php/const Biblioverse\TypesenseBundle\BiblioverseTypesenseBundle::ENTITY_TRANSFORMER_TAG_NAME, index_by: 'key' }
      $entityMapping: '%biblioverse_typesense.config.entity_mapping%'

  Biblioverse\TypesenseBundle\Mapper\Locator\MapperLocatorInterface: '@Biblioverse\TypesenseBundle\Mapper\Locator\MapperLocator'

  Biblioverse\TypesenseBundle\CollectionAlias\CollectionAlias: ~
  Biblioverse\TypesenseBundle\CollectionAlias\CollectionAliasInterface:  '@Biblioverse\TypesenseBundle\CollectionAlias\CollectionAlias'

  Biblioverse\TypesenseBundle\Command\:
    resource: '../../Command/'
    tags: ['console.command']

  biblioverse_typesense.collection.abstract:
    class: Biblioverse\TypesenseBundle\Search\SearchCollection
    abstract: true


  biblioverse_typesense.entity_transformer.abstract:
    class: Biblioverse\TypesenseBundle\Mapper\Entity\EntityTransformer
    abstract: true

  biblioverse_typesense.entity_mapper_generator.abstract:
    class: Biblioverse\TypesenseBundle\Mapper\Entity\EntityMapperGenerator
    abstract: true

  biblioverse_typesense.entity_data_generator.abstract:
    class: Biblioverse\TypesenseBundle\Mapper\Entity\EntityDataGenerator
    abstract: true

  Biblioverse\TypesenseBundle\Mapper\Entity\Identifier\EntityIdentifier: ~
  Biblioverse\TypesenseBundle\Mapper\Entity\Identifier\EntityIdentifierInterface: '@Biblioverse\TypesenseBundle\Mapper\Entity\Identifier\EntityIdentifier'

  Biblioverse\TypesenseBundle\Search\Search: ~

  Biblioverse\TypesenseBundle\Indexer\Indexer:
  Biblioverse\TypesenseBundle\Indexer\IndexerInterface:
    alias: 'Biblioverse\TypesenseBundle\Indexer\Indexer'
    public: true

  Biblioverse\TypesenseBundle\Search\Hydrate\HydrateSearchResult:
    autowire: true

  Biblioverse\TypesenseBundle\Search\Hydrate\HydrateSearchResultInterface: '@Biblioverse\TypesenseBundle\Search\Hydrate\HydrateSearchResult'

  Biblioverse\TypesenseBundle\EventSubscriber\IndexCollectionSubscriber:
    autowire: true
    arguments:
      $enabled: '%biblioverse_typesense.config.auto_update%'
    tags:
      - { name: doctrine.event_subscriber, connection: default }
