name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
env:
  TEST_TAG: "typesensebundle:test"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.TEST_TAG }}
          load: true # don't push to registry but to local docker engine
      - name: Test image
        run: |
          docker run --rm ${{ env.TEST_TAG }} php -v